import { REACT_APP_HTTPS } from "env";
const http = REACT_APP_HTTPS;

export const databases = {
    register: `${http}/auth/register`,
    login: `${http}/auth/login`,
    addOrDeleteMarker: `${http}/addOrDeleteMarker`,
    getOwnMarker: `${http}/getOwnMarker`,
    addOwnMarker: `${http}/addOwnMarker`,
    changeOwnMarker: `${http}/changeOwnMarker`,
    deleteOwnMarker: `${http}/deleteOwnMarker`,
};

export const typePlaces = [
    { label: "Accounting", value: "Accounting" },
    { label: "Airport", value: "Airport" },
    { label: "Amusement Park", value: "Amusement Park" },
    { label: "Aquarium", value: "Aquarium" },
    { label: "Art Gallery", value: "Art Gallery" },
    { label: "ATM", value: "ATM" },
    { label: "Bakery", value: "Bakery" },
    { label: "Bank", value: "Bank" },
    { label: "Bar", value: "Bar" },
    { label: "Beauty Salon", value: "Beauty Salon" },
    { label: "Bicycle Store", value: "Bicycle Store" },
    { label: "Book Store", value: "Book Store" },
    { label: "Bowling Alley", value: "Bowling Alley" },
    { label: "Bus Station", value: "Bus Station" },
    { label: "Cafe", value: "Cafe" },
    { label: "Campground", value: "Campground" },
    { label: "Car Dealer", value: "Car Dealer" },
    { label: "Car Rental", value: "Car Rental" },
    { label: "Car Repair", value: "Car Repair" },
    { label: "Car Wash", value: "Car Wash" },
    { label: "Casino", value: "Casino" },
    { label: "Cemetery", value: "Cemetery" },
    { label: "Church", value: "Church" },
    { label: "City Hall", value: "City Hall" },
    { label: "Clothing Store", value: "Clothing Store" },
    { label: "Convenience Store", value: "Convenience Store" },
    { label: "Courthouse", value: "Courthouse" },
    { label: "Dentist", value: "Dentist" },
    { label: "Department Store", value: "Department Store" },
    { label: "Doctor", value: "Doctor" },
    { label: "Drugstore", value: "Drugstore" },
    { label: "Electrician", value: "Electrician" },
    { label: "Electronics Store", value: "Electronics Store" },
    { label: "Embassy", value: "Embassy" },
    { label: "Fire Station", value: "Fire Station" },
    { label: "Florist", value: "Florist" },
    { label: "Funeral Home", value: "Funeral Home" },
    { label: "Furniture Store", value: "Furniture Store" },
    { label: "Gas Station", value: "Gas Station" },
    { label: "Gym", value: "Gym" },
    { label: "Hair Care", value: "Hair Care" },
    { label: "Hardware Store", value: "Hardware Store" },
    { label: "Hindu Temple", value: "Hindu Temple" },
    { label: "Home Goods Store", value: "Home Goods Store" },
    { label: "Hospital", value: "Hospital" },
    { label: "Insurance Agency", value: "Insurance Agency" },
    { label: "Jewelry Store", value: "Jewelry Store" },
    { label: "Laundry", value: "Laundry" },
    { label: "Lawyer", value: "Lawyer" },
    { label: "Library", value: "Library" },
    { label: "Light Rail Station", value: "Light Rail Station" },
    { label: "Liquor Store", value: "Liquor Store" },
    { label: "Local Government Office", value: "Local Government Office" },
    { label: "Locksmith", value: "Locksmith" },
    { label: "Lodging", value: "Lodging" },
    { label: "Meal Delivery", value: "Meal Delivery" },
    { label: "Meal Takeaway", value: "Meal Takeaway" },
    { label: "Mosque", value: "Mosque" },
    { label: "Movie Rental", value: "Movie Rental" },
    { label: "Movie Theater", value: "Movie Theater" },
    { label: "Moving Company", value: "Moving Company" },
    { label: "Museum", value: "Museum" },
    { label: "Night Club", value: "Night Club" },
    { label: "Painter", value: "Painter" },
    { label: "Park", value: "Park" },
    { label: "Parking", value: "Parking" },
    { label: "Pet Store", value: "Pet Store" },
    { label: "Pharmacy", value: "Pharmacy" },
    { label: "Physiotherapist", value: "Physiotherapist" },
    { label: "Plumber", value: "Plumber" },
    { label: "Police", value: "Police" },
    { label: "Post Office", value: "Post Office" },
    { label: "Primary School", value: "Primary School" },
    { label: "Real Estate Agency", value: "Real Estate Agency" },
    { label: "Restaurant", value: "Restaurant" },
    { label: "Roofing Contractor", value: "Roofing Contractor" },
    { label: "RV Park", value: "RV Park" },
    { label: "School", value: "School" },
    { label: "Secondary School", value: "Secondary School" },
    { label: "Shoe Store", value: "Shoe Store" },
    { label: "Shopping Mall", value: "Shopping Mall" },
    { label: "Spa", value: "Spa" },
    { label: "Stadium", value: "Stadium" },
    { label: "Storage", value: "Storage" },
    { label: "Store", value: "Store" },
    { label: "Subway Station", value: "Subway Station" },
    { label: "Supermarket", value: "Supermarket" },
    { label: "Synagogue", value: "Synagogue" },
    { label: "Taxi Stand", value: "Taxi Stand" },
    { label: "Tourist Attraction", value: "Tourist Attraction" },
    { label: "Train Station", value: "Train Station" },
    { label: "Transit Station", value: "Transit Station" },
    { label: "Travel Agency", value: "Travel Agency" },
    { label: "University", value: "University" },
    { label: "Veterinary Care", value: "Veterinary Care" },
    { label: "Zoo", value: "Zoo" },
];
