import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        width: "100%",
        position: "absolute",
        bottom: 0,
        left: 0,
    },
    tabBar: {
        width: "100%",
        height: 80,
        backgroundColor: "#F9FFFF",
        position: "absolute",
        bottom: 0,
        left: 0,
        flex: 1,
        zIndex: 1,
        borderRadius: 10,
        padding: 5,
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        shadowColor: "#313866",
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    img: {
        width: 40,
        height: 40,
    },
    routeImg: {
        width: 40,
        height: 40,
    },
    button: {
        height: 70,
        backgroundColor: "#313866",
        position: "absolute",
        width: "20%",
        bottom: 100,
        right: 0,
        zIndex: 1,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        borderBottomLeftRadius: 10,
        borderTopLeftRadius: 10,
        shadowOffset: { width: -2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    navigationButton: {
        maxWidth: 80,
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
    },
    containerToggleSwitch: {
        position: "absolute",
        bottom: 185,
        right: 0,
        display: "flex",
        flexDirection: "row",
    },
    containerForTraveling: {
        width: "70%",
        zIndex: 1,
        position: "absolute",
        bottom: 185,
        left: 0,
        borderBottomRightRadius: 10,
        borderTopRightRadius: 10,
        backgroundColor: "#F9FFFF",
        shadowColor: "#313866",
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        display: "flex",
        flexDirection: "row",
        alignContent: "center",
    },
    containerBuuttonsNextPrevious: {
        display: "flex",
        flexDirection: "row",
        backgroundColor: "#313866",
    },
    containerText: {
        display: "flex",
        height: "100%",
        justifyContent: "center",
        alignContent: "center",
        marginLeft: 20,
    },
    text: {
        fontSize: 20,
        color: "#313866",
    },
    link: {
        position: "absolute",
        bottom: 79,
        left: 5,
        display: "flex",
        flexDirection: "row",
        zIndex: 100,
    },
});

export default styles;
